version: '3.8'

services:
  media-manager:
    build: .
    container_name: media-manager
    ports:
      - "5000:5000"
    volumes:
      - /home/erwan/docker/media/movies:/movies
      - /home/erwan/docker/media:/tv
      - /home/erwan/docker/downloads:/downloads
    environment:
      - RADARR_URL=http://192.168.1.146:7878
      - RADARR_API_KEY=19f0730c4619433c973bed6186f7dcef
    restart: unless-stopped
